import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useAppDispatch, useAppSelector } from '../redux/hooks/redux'
import { userSlice } from '../redux/store/reducers/UserSlice'
import styles from '../styles/Home.module.css'
import { fetchUsers } from '../redux/store/reducers/ActionCreators'
import PostContainer from '../components/PostContainer'
import PostContainer2 from '../components/PostContainer2'

const Home: NextPage = () => {
  // const dispatch = useAppDispatch()
  // const { users, isLoading, error } = useAppSelector(state => state.userReducer)

  // React.useEffect(() => {
  //   dispatch(fetchUsers())
  // }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{display: "flex"}}>
        <PostContainer />
        <PostContainer2 />
      </div>

      {/* {isLoading && <h1>Идёт загрузка</h1>}
      {error && <h1>{error}</h1>}
      <p>{JSON.stringify(users, null, 3)}</p> */}

    </div>
  )
}

export default Home
